name: Build and Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore persistence.sln
      - name: Build
        run: dotnet build persistence.sln --no-restore
      - name: Test
        run: dotnet test persistence.sln --no-build --verbosity normal
